# Generated by Django 4.2.14 on 2024-07-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
